### PR TITLE
Add new format to parse test

### PR DESCRIPTION
**Pull request by us3r64**
#91

### CODE REVIEW

**Comment by jlaffaye** [comment]
I am unsure what you are trying to achieve.
Your PR broke the tests.

**Comment by us3r64** [comment]
that was the point, to give you the failing FTP response format for whom the parsing is failing

**Comment by corny** [comment]
What is different from other formats?
* 2nd field numeric
* 3rd field non-numeric
* 4th field numeric

It's not easy to distinguish.

**Comment by corny** [comment]
@jlaffaye please close this issue due to inactivity

**Pull request closed without merging**
