### PR TITLE
Respect the timeout for dialing

### LINKED ISSUE #112: ReadResponse(StatusReady)  in DialTimeout hang
https://github.com/jlaffaye/ftp/blob/master/ftp.go#L88

Hi,

my program have multiple connections to  LIST different directories per second and the ftp server is Serv-U  v5.0. after a while, some connections hang.  netstat command shows that the tcp state is ESTABLISHED. run ftp.DialTimeout with some duration does not help.

```golang
func ftpListDirectory(path string) ([]*ftp.Entry, error) {
	conn, err := ftp.DialTimeout(cfg.FtpSrvAddr, 5*time.Second)
	if err != nil {
		return nil, err
	}
	conn.DisableEPSV = true
	defer conn.Quit()

	if err = conn.Login(cfg.FtpSrvUser, cfg.FtpSrvPwd); err != nil {
		return nil, err
	}

	return conn.List(path)
}
```

### LINKED ISSUE #132: Blocking at DialTimeout() -> time.Second*5 : FTP runnning at localhost:20
The code is blocking at DialTimeout - with a timeout of time.Second*5; The connection never goes through nor does it return with an error

### LINKED ISSUE #147: blocked when ftp client try to connect to a no-return tcp server
**Describe the bug**
If the server is not returning something.
It blocks when the client tries to read something(`StatusReady`) from the server after the TCP connection is done.

**To Reproduce**

One simple example:
`ftp www.google.com 80`

**Expected behavior**
The client blocks.

**FTP server**

any non-return TCP server

**Debug output**

**Additional context**

https://github.com/jlaffaye/ftp/blob/8f5b34ce006f202b0a67111d675395f44fd94d21/ftp.go#L125

### LINKED ISSUE #181: Illegal port, wait indefinitely
eg: ssh port
```
c, err := ftp.Dial("ftp.example.org:22", ftp.DialWithTimeout(5*time.Second))
if err != nil {
    log.Fatal(err)
}
```

### PR DESCRIPTION
**Pull request by corny**
fixes #112, fixes #132, fixes #147, fixes #181

### CODE REVIEW

**Comment by jlaffaye** [comment]
What we currently have is a connect timeout.
What you are suggesting is a timeout for the whole function after the connect. I think we should set the deadline before each operation, making it a read and write timeout.
Then we can say `DialWithTimeout` = connect/read/write and can introduce later more configurations to set the connect, read and write timeouts separately if needed.

**Comment by corny** [comment]
When some calls `ftp.DialTimeout()` he/she expects that this method returns not later than after the given time period. This is what people describe in the related issues. I think it's not important to set specific timeouts because there are many possibilities:
* TCP connect/read/write
* (optional) TLS handshake
* waiting for the first line
* MLST command

**Comment by jlaffaye** [comment]
> When some calls ftp.DialTimeout() he/she simply expects that this method returns not later than after the given duration.

Then the expectation is wrong :) If you want to guard the entire execution time of a function, it should be done with a context.

> I think it's not important to set specific timeouts because there are many possibilities

I was saying that we could do that in the future when needed.

> The current DialTimeout method just stucks which is really bad. It should never stuck.

Agreed. But with a correct read/write timeout it will handle that.

**Comment by corny** [comment]
Unfortunately neither the `textproto` package nor the `tls` package of Go 1.14 supports a context.

Do your suggest to use the `timeout` as temporary read/write timeout during the `DialTimeout` call? Nevertheless the method can take much longer to return if it's not a deadline.

**Pull request closed without merging**
