### PR TITLE
fix_walk

### PR DESCRIPTION
**Pull request by vcraescu**
Walker is not walking at all. :)

### CODE REVIEW

**Comment by vcraescu** [comment]
@jlaffaye you will accept this pr?

**Comment by vcraescu** [comment]
bump 😁

**Comment by vcraescu** [comment]
@jlaffaye bump

**Comment by jawr** [comment]
I think there are issues with this, if you try walk a directory with 1 file it doesn't work. It also trims the leading '/' from the root path.

**Pull request merged**
