### PR TITLE
Use testify to simplify tests

### PR DESCRIPTION
**Pull request by corny**

### CODE REVIEW

**Comment by shurcooL** [comment]
I think this change makes it harder to read the test code, not easier. I would advise against doing this.

See https://www.youtube.com/watch?v=yi5A3cK1LNA for some motivation.

**Comment by corny** [comment]
For me it makes the tests easier to read. Dozens of `if err != nil { t.Error(err) }` is just boiler code for me. I think this is just a personal preference.

**Comment by shurcooL** [comment]
I agree that it's a personal preference.

Given this is an open-source Go package that many people should use, understand, be able to contribute to, I think it makes sense to favor the Go style and use greatest common denominator, something that everyone can understand and read easily, which is simple `if` statements and `testing` package from standard library.

At least that's my recommendation. I don't contribute to this library that much, and you've made [numerous contributions](https://github.com/jlaffaye/ftp/commits/master?author=corny), so your opinion should carry greater weight.

**Comment by corny** [comment]
@jlaffaye your opinion?

**Comment by jlaffaye** [comment]
I would rather stay with the idiomatic code.

**Comment by corny** [comment]
Ok, thanks for comment.

**Pull request closed without merging**
