### PR TITLE
 Use MLST if supported

### PR DESCRIPTION
**Pull request by corny**
Since vsftpd does not support MLST, I added ProFTPD.

Further improvements:
- Test vsftpd and proftpd in parallel
- Use Ubuntu 14.04 instead of 12.04

closes #46

### CODE REVIEW

**Comment by corny** [comment]
@jlaffaye please review

**Comment by etix** [comment]
@jlaffaye if you're not actively working on this project anymore you should consider giving commit access to contributors like @corny.

**Comment by corny** [comment]
I asked @jlaffaye in november for commit access, but I haven't received a response so far.

**Comment by corny** [comment]
@jlaffaye ping

**Comment by corny** [comment]
thanks!

**Pull request merged**
