### PR TITLE
blocked when ftp client try to connect to a no-return tcp server

### PR DESCRIPTION
**Pull request by qudongfang**
#147

### CODE REVIEW

**Comment by corny** [comment]
As far as I understand `SetDeadline()` the deadline is also used for all future read and write operations on the socket. Am I wrong?

**Comment by phoenix147** [comment]
The problem with this is approach is, that 
a) the deadline is a hard deadline, e.g. a fixed time after which an error is returned
b) as @corny stated, the deadline is for all existing and future read and write operations

so for this to work, on every successful connect/read/write operation, the deadline has to be extended or disabled

**Comment by qudongfang** [comment]
@corny  @phoenix147 
Yes, You are right. The earlier approach is not right.

**Comment by jlaffaye** [comment]
What is the problem with https://godoc.org/github.com/jlaffaye/ftp#DialWithTimeout ?

**Pull request closed without merging**
