### PR TITLE
Add Stat based on MLST command

### PR DESCRIPTION
**Pull request by panthony**
Hi,

The idea of this new method is provide a more efficient way to lookup a single entry when supported by the remote server.

I exposed a new `ErrNotSupported` error to ease the detection of an unsupported method & implement a fallback strategy.

There is a subtle difference between MLST and MLSD, the former has a space in front of each line entry (except BEGIN/END), I was not sure if the trim should be done here or in `parseRFC3659ListLine`.

I'm not sure if `Stat` is the appropriate name though, it matches the commonly used `os.Stat()` function but there *is* a `STAT` FTP command (that does something else entirely.)

### CODE REVIEW

**Comment by ncw** [comment]
Very useful thank you :-)

**Comment by jlaffaye** [comment]
Can you please add a test case for this new function ?
Also, I agree, we should come with a better name since Stat is confusing.

**Comment by panthony** [comment]
Could be `GetEntry`, `GetEntryInfo`, ..

For the test there are none for the `ftp.go` file thus I'm not quite sure how to bootstrap one, I'll try to get a look if I got the time.

**Comment by panthony** [comment]
Would `GetEntryInfo` be fine?

**Comment by jlaffaye** [comment]
Dup: https://github.com/jlaffaye/ftp/pull/269

**Pull request closed without merging**
