### PR TITLE
added recursively deleting (non-empty) folders

### PR DESCRIPTION
**Pull request by Mojachieee**
Added the ability to remove folders recursively 
#81

### CODE REVIEW

**Comment by corny** [comment]
Please also add a test to the `client_test.go`.
The test coverage should increase then.

**Comment by Mojachieee** [comment]
@corny 
I'm having trouble testing a few codepaths. Do you have any advice on how I could test these?

**Comment by corny** [comment]
The missing codepaths are quite hard to test. They probably can only be tested with a stubbed server. Your PR and the test coverage looks fine to me.

One last thing: Please use different names for your test folders inside `incoming` for each test case. That makes the tests less dependent from each other.

**Comment by corny** [comment]
:+1:

**Comment by jlaffaye** [comment]
Can you squash your commits ?

**Comment by Mojachieee** [comment]
Done :)

**Pull request merged**
